permalink: /:categories/:title/

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.markdown
  - s3_website.yml
  - .jekyll-metadata
  - .asset-cache
  - .sass-cache
  - .git

# configuration options https://github.com/ixti/jekyll-assets
assets:
  cdn: http://d3bzjcbbiattc5.cloudfront.net
  prefix: "/assets"
  assets:
    - "christmas-lights.png"
  sources:
    - _assets/js
    - _assets/js/vendor
    - _assets/css
    - _assets/css/custom
    - _assets/img
    - _assets/img/headshots
    - _assets/img/posts
    - _assets/img/pages
  features:
    liquid: true
